export const TEMP_QUOTATIONS = [
  {
    id: 'temp-q-1001',
    quote_number: 'DF-1001',
    customer: { name: 'Northstar Labs' },
    created_by: { full_name: 'Maya Chen' },
    currency: 'USD',
    grand_total: '48200.00',
    total_cost: '35186.00',
    gross_margin: '27.0',
    risk_score: '28',
    status: 'PENDING_APPROVAL',
    created_at: '2026-09-02T09:30:00Z',
    approval_chain: [
      { approval_level: 'MANAGER', status: 'PENDING' },
      { approval_level: 'MANAGER_FINANCE', status: 'PENDING' },
    ],
  },
  {
    id: 'temp-q-1002',
    quote_number: 'DF-1002',
    customer: { name: 'Atlas Commerce' },
    created_by: { full_name: 'Jordan Lee' },
    currency: 'USD',
    grand_total: '19600.00',
    total_cost: '14112.00',
    gross_margin: '28.0',
    risk_score: '12',
    status: 'APPROVED',
    created_at: '2026-08-28T14:15:00Z',
    approval_chain: [
      { approval_level: 'MANAGER', status: 'APPROVED', acted_by_user_id: 'temp-manager' },
      { approval_level: 'MANAGER_FINANCE', status: 'APPROVED' },
    ],
  },
  {
    id: 'temp-q-1003',
    quote_number: 'DF-1003',
    customer: { name: 'Juniper Health' },
    created_by: { full_name: 'Maya Chen' },
    currency: 'USD',
    grand_total: '73500.00',
    total_cost: '59535.00',
    gross_margin: '19.0',
    risk_score: '67',
    status: 'DRAFT',
    created_at: '2026-09-04T11:05:00Z',
    approval_chain: [],
  },
  {
    id: 'temp-q-1004',
    quote_number: 'DF-1004',
    customer: { name: 'Monument Energy' },
    created_by: { full_name: 'Jordan Lee' },
    currency: 'USD',
    grand_total: '31200.00',
    total_cost: '24648.00',
    gross_margin: '21.0',
    risk_score: '58',
    status: 'SENT',
    created_at: '2026-08-22T10:45:00Z',
    approval_chain: [
      { approval_level: 'MANAGER', status: 'REJECTED', acted_by_user_id: 'temp-manager' },
    ],
  },
];

export const TEMP_DASHBOARD_DATA = TEMP_QUOTATIONS.map((quotation) => ({
  ...quotation,
  customer: quotation.customer ? { ...quotation.customer } : undefined,
  created_by: quotation.created_by ? { ...quotation.created_by } : undefined,
  approval_chain: quotation.approval_chain.map((approval) => ({ ...approval })),
}));