"""add product catalog and price lists

Revision ID: 344e87235878
Revises: d4e5f6a7b8c9
Create Date: 2026-09-05 18:06:55.455119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344e87235878'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_notes_customer_id'), 'credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.drop_index(op.f('invoice_number'), table_name='invoices')
    op.drop_index(op.f('order_number'), table_name='orders')
    op.create_index('ix_payment_invoice_status', 'payments', ['invoice_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_invoice_status', table_name='payments')
    op.create_index(op.f('order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_customer_id'), table_name='credit_notes')
    # ### end Alembic commands ###
