"""add upsell cross sell recommendations

Revision ID: 468b1c6ebb50
Revises: bbc3bea90c5f
Create Date: 2026-09-05 20:55:46.643103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468b1c6ebb50'
down_revision: Union[str, Sequence[str], None] = 'bbc3bea90c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_recommendation_rules',
    sa.Column('source_product_id', sa.String(length=36), nullable=False),
    sa.Column('suggested_product_id', sa.String(length=36), nullable=False),
    sa.Column('co_purchase_count', sa.Integer(), nullable=False),
    sa.Column('recommendation_weight', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('minimum_margin_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_product_id', 'suggested_product_id', name='uq_recommendation_source_suggested')
    )
    op.create_index(op.f('ix_product_recommendation_rules_source_product_id'), 'product_recommendation_rules', ['source_product_id'], unique=False)
    op.create_index(op.f('ix_product_recommendation_rules_suggested_product_id'), 'product_recommendation_rules', ['suggested_product_id'], unique=False)
    op.create_table('promotions',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ranking_boost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_product_id'), 'promotions', ['product_id'], unique=False)
    op.create_table('recommendation_events',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('source_product_id', sa.String(length=36), nullable=False),
    sa.Column('suggested_product_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suggested_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_events_quotation_id'), 'recommendation_events', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_source_product_id'), 'recommendation_events', ['source_product_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_suggested_product_id'), 'recommendation_events', ['suggested_product_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_user_id'), 'recommendation_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_events_user_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_suggested_product_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_source_product_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_quotation_id'), table_name='recommendation_events')
    op.drop_table('recommendation_events')
    op.drop_index(op.f('ix_promotions_product_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_product_recommendation_rules_suggested_product_id'), table_name='product_recommendation_rules')
    op.drop_index(op.f('ix_product_recommendation_rules_source_product_id'), table_name='product_recommendation_rules')
    op.drop_table('product_recommendation_rules')
    # ### end Alembic commands ###
