"""add discount governance and approval chains

Revision ID: 592d7d57a8ab
Revises: 344e87235878
Create Date: 2026-09-05 19:03:29.778652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592d7d57a8ab'
down_revision: Union[str, Sequence[str], None] = '344e87235878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_chains',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_chains_name'), 'approval_chains', ['name'], unique=True)
    op.create_table('approval_bands',
    sa.Column('approval_chain_id', sa.String(length=36), nullable=False),
    sa.Column('min_excess_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_excess_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approval_level', sa.Enum('MANAGER', 'MANAGER_FINANCE', name='approvallevel', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_chain_id'], ['approval_chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_bands_approval_chain_id'), 'approval_bands', ['approval_chain_id'], unique=False)
    op.create_table('discount_rules',
    sa.Column('customer_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', name='customertier', native_enum=False, length=20), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('approval_chain_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_chain_id'], ['approval_chains.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rules_approval_chain_id'), 'discount_rules', ['approval_chain_id'], unique=False)
    op.create_index(op.f('ix_discount_rules_category_id'), 'discount_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_discount_rules_customer_tier'), 'discount_rules', ['customer_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_rules_customer_tier'), table_name='discount_rules')
    op.drop_index(op.f('ix_discount_rules_category_id'), table_name='discount_rules')
    op.drop_index(op.f('ix_discount_rules_approval_chain_id'), table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_approval_bands_approval_chain_id'), table_name='approval_bands')
    op.drop_table('approval_bands')
    op.drop_index(op.f('ix_approval_chains_name'), table_name='approval_chains')
    op.drop_table('approval_chains')
    # ### end Alembic commands ###
