"""add warehouse inventory and fulfillment

Revision ID: 598d828fb7e5
Revises: 468b1c6ebb50
Create Date: 2026-09-05 22:27:03.830617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598d828fb7e5'
down_revision: Union[str, Sequence[str], None] = '468b1c6ebb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('shipping_fixed_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('shipping_cost_weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_table('fulfillment_plans',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'BACKORDERED', 'CANCELLED', name='fulfillmentplanstatus', native_enum=False, length=30), nullable=False),
    sa.Column('estimated_shipment_count', sa.Integer(), nullable=False),
    sa.Column('estimated_shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_plans_quotation_id'), 'fulfillment_plans', ['quotation_id'], unique=True)
    op.create_table('inventory_stock',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'variant_id', name='uq_inventory_warehouse_product_variant')
    )
    op.create_index(op.f('ix_inventory_stock_product_id'), 'inventory_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_variant_id'), 'inventory_stock', ['variant_id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_warehouse_id'), 'inventory_stock', ['warehouse_id'], unique=False)
    op.create_table('replenishment_rules',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('max_stock', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'variant_id', name='uq_replenishment_warehouse_product_variant')
    )
    op.create_index(op.f('ix_replenishment_rules_product_id'), 'replenishment_rules', ['product_id'], unique=False)
    op.create_index(op.f('ix_replenishment_rules_variant_id'), 'replenishment_rules', ['variant_id'], unique=False)
    op.create_index(op.f('ix_replenishment_rules_warehouse_id'), 'replenishment_rules', ['warehouse_id'], unique=False)
    op.create_table('backorders',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('quote_line_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ALLOCATED', 'FULFILLED', 'CANCELLED', name='backorderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('expected_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backorders_quotation_id'), 'backorders', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_backorders_quote_line_id'), 'backorders', ['quote_line_id'], unique=False)
    op.create_index(op.f('ix_backorders_status'), 'backorders', ['status'], unique=False)
    op.create_table('fulfillment_allocations',
    sa.Column('fulfillment_plan_id', sa.String(length=36), nullable=False),
    sa.Column('quote_line_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('fulfilled_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('shipment_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='fulfillmentallocationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fulfillment_plan_id'], ['fulfillment_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_allocations_fulfillment_plan_id'), 'fulfillment_allocations', ['fulfillment_plan_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_allocations_quote_line_id'), 'fulfillment_allocations', ['quote_line_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_allocations_warehouse_id'), 'fulfillment_allocations', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulfillment_allocations_warehouse_id'), table_name='fulfillment_allocations')
    op.drop_index(op.f('ix_fulfillment_allocations_quote_line_id'), table_name='fulfillment_allocations')
    op.drop_index(op.f('ix_fulfillment_allocations_fulfillment_plan_id'), table_name='fulfillment_allocations')
    op.drop_table('fulfillment_allocations')
    op.drop_index(op.f('ix_backorders_status'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_quote_line_id'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_quotation_id'), table_name='backorders')
    op.drop_table('backorders')
    op.drop_index(op.f('ix_replenishment_rules_warehouse_id'), table_name='replenishment_rules')
    op.drop_index(op.f('ix_replenishment_rules_variant_id'), table_name='replenishment_rules')
    op.drop_index(op.f('ix_replenishment_rules_product_id'), table_name='replenishment_rules')
    op.drop_table('replenishment_rules')
    op.drop_index(op.f('ix_inventory_stock_warehouse_id'), table_name='inventory_stock')
    op.drop_index(op.f('ix_inventory_stock_variant_id'), table_name='inventory_stock')
    op.drop_index(op.f('ix_inventory_stock_product_id'), table_name='inventory_stock')
    op.drop_table('inventory_stock')
    op.drop_index(op.f('ix_fulfillment_plans_quotation_id'), table_name='fulfillment_plans')
    op.drop_table('fulfillment_plans')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
