"""add quote approval workflow and audit logs

Revision ID: bbc3bea90c5f
Revises: c77d82a43d3c
Create Date: 2026-09-05 19:54:18.492767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc3bea90c5f'
down_revision: Union[str, Sequence[str], None] = 'c77d82a43d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('quote_approvals',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('approval_version', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approval_level', sa.Enum('MANAGER', 'MANAGER_FINANCE', name='approvallevel', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', name='approvalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('acted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_approvals_approval_version'), 'quote_approvals', ['approval_version'], unique=False)
    op.create_index(op.f('ix_quote_approvals_quotation_id'), 'quote_approvals', ['quotation_id'], unique=False)
    op.add_column('quotations', sa.Column('approval_level_required', sa.String(length=30), nullable=True))
    op.add_column('quotations', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('approval_version', sa.Integer(), nullable=False))
    op.add_column('quotations', sa.Column('last_evaluated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'last_evaluated_at')
    op.drop_column('quotations', 'approval_version')
    op.drop_column('quotations', 'rejected_at')
    op.drop_column('quotations', 'approved_at')
    op.drop_column('quotations', 'submitted_at')
    op.drop_column('quotations', 'approval_level_required')
    op.drop_index(op.f('ix_quote_approvals_quotation_id'), table_name='quote_approvals')
    op.drop_index(op.f('ix_quote_approvals_approval_version'), table_name='quote_approvals')
    op.drop_table('quote_approvals')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
