"""add customer portal negotiation

Revision ID: d975dbe62f48
Revises: 598d828fb7e5
Create Date: 2026-09-05 22:51:54.110873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd975dbe62f48'
down_revision: Union[str, Sequence[str], None] = '598d828fb7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_sessions',
    sa.Column('customer_contact_id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_contact_id'], ['customer_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_portal_sessions_customer_contact_id'), 'portal_sessions', ['customer_contact_id'], unique=False)
    op.create_index(op.f('ix_portal_sessions_quotation_id'), 'portal_sessions', ['quotation_id'], unique=False)
    op.create_table('negotiation_requests',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('customer_contact_id', sa.String(length=36), nullable=False),
    sa.Column('quote_line_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('requested_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='negotiationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_contact_id'], ['customer_contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_requests_customer_contact_id'), 'negotiation_requests', ['customer_contact_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_quotation_id'), 'negotiation_requests', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_quote_line_id'), 'negotiation_requests', ['quote_line_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_status'), 'negotiation_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_requests_status'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_quote_line_id'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_quotation_id'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_customer_contact_id'), table_name='negotiation_requests')
    op.drop_table('negotiation_requests')
    op.drop_index(op.f('ix_portal_sessions_quotation_id'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_customer_contact_id'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    # ### end Alembic commands ###
